export enum tagTypes {
  user = "users",
  style = "style",
  orders = "orders",
  courier = "courier",
  ppStatus = "pp-status",
  bulkStatus = "bulk-status",
  factory = "factory",
  port = "port",
  items = "items",
  ppSubmission = "pp-submission-date",
  ldCpAopStrikeOff = "ld-cp-aop-strike-off",
  notification = "notification",
  reportedProblems = "reportedProblems",
}

export const tagTypesList = [
  tagTypes.user,
  tagTypes.style,
  tagTypes.orders,
  tagTypes.courier,
  tagTypes.ppStatus,
  tagTypes.bulkStatus,
  tagTypes.factory,
  tagTypes.port,
  tagTypes.items,
  tagTypes.courier,
  tagTypes.ppSubmission,
  tagTypes.ldCpAopStrikeOff,
  tagTypes.notification,
  tagTypes.reportedProblems,
];
