export const productData = [
  {
    id: 1,
    year: 2016,
    month: "Apr",
    thisYearOrders: 46,
    lastYearOrders: 56,
    twoYearsAgoOrders: 46,
  },
  {
    id: 2,
    year: 2017,
    month: "May",
    thisYearOrders: 96,
    lastYearOrders: 45,
    twoYearsAgoOrders: 66,
  },
  {
    id: 3,
    year: 2018,
    month: "June",
    thisYearOrders: 78,
    lastYearOrders: 56,
    twoYearsAgoOrders: 36,
  },
  {
    id: 4,
    year: 2019,
    month: "July",
    thisYearOrders: 56,
    lastYearOrders: 35,
    twoYearsAgoOrders: 76,
  },
  {
    id: 5,
    year: 2020,
    month: "Aug",
    thisYearOrders: 56,
    lastYearOrders: 100,
    twoYearsAgoOrders: 96,
  },
  {
    id: 6,
    year: 2020,
    month: "Sep",
    thisYearOrders: 54,
    lastYearOrders: 79,
    twoYearsAgoOrders: 26,
  },
  {
    id: 7,
    year: 2020,
    month: "Oct",
    thisYearOrders: 4,
    lastYearOrders: 56,
    twoYearsAgoOrders: 76,
  },
  {
    id: 8,
    year: 2020,
    month: "Nov",
    thisYearOrders: 56,
    lastYearOrders: 99,
    twoYearsAgoOrders: 86,
  },
  {
    id: 9,
    year: 2020,
    month: "Dec",
    thisYearOrders: 4,
    lastYearOrders: 56,
    twoYearsAgoOrders: 46,
  },
  {
    id: 10,
    year: 2020,
    month: "Jan",
    thisYearOrders: 67,
    lastYearOrders: 56,
    twoYearsAgoOrders: 86,
  },
  {
    id: 11,
    year: 2020,
    month: "Feb",
    thisYearOrders: 4,
    lastYearOrders: 56,
    twoYearsAgoOrders: 56,
  },
  {
    id: 12,
    year: 2020,
    month: "Mar",
    thisYearOrders: 56,
    lastYearOrders: 68,
    twoYearsAgoOrders: 46,
  },
];
